version: '3'

silent: true

tasks:

  gen:
    desc: Generates histogram
    cmds:
      - cmd: cargo +stable run
      - cmd: convert -size 2000x600 data/benchmarks.svg data/benchmarks.png

  build:
    desc: Builds in debug mode
    cmds:
      - cmd: cargo +stable build

  clean:
    desc: Cleans all targets
    cmds:
      - cmd: cargo clean

  clippy:
    desc: Runs clippy for all targets
    cmds:
      - cmd: cargo +nightly clippy --workspace --all-targets